### ISSUE TITLE
Support for multiple moods

### ISSUE THREAD

**Issue by anthx** [MichaelCurrin/daylio-csv-parser#20]
I can understand why it doesn't support it, it's not straight forward. I have an idea how to make it work, but I'd need to experiment a while longer. I have multiple moods added so I'd like it to work for myself, happy to write it. I think it'd need to be a multistage process - restructure the conf moods so they can store a list, then first process those lists into a big dictionary as {str: int} . Like when the script loads, process the CONF moods into a list for each mood number, then into a dictionary and finally call that dictionary to do the normal translation.

**Comment by MichaelCurrin** [comment]
Hi.

Thanks for the interest.

So you mean instead of mood1 to mood5, you can have more than 5 and it would be a list?

Yes that sounds good.

**Comment by MichaelCurrin** [comment]
So storage would be

```yaml
mood_labels:
  - very very bad # 1
  - very bad
  - bad
  - average
  - good
  - very good
  - very very good # 7

```

Then a dict comprehension.

```python
moods = {i+1: label for i, label in enumerate(mood_labels)}
moods[1]
# very very bad
moods[7] very very good
```

**Comment by MichaelCurrin** [comment]
Which I guess is effectively a list that starts at 1 instead of 0 and has no list operations which is fine as it will be kept frozen

**Comment by anthx** [comment]
I was thinking of keeping mood scores 1 - 5 and essentially just throwing away the extra data. Daylio itself treats each colour the same numerically anyway. And your math works out the same. Only problem is the loss of information. (But that's OK, as long as we warn the user.)

 I have Good and Refreshed, which to me mean different things, but they are both green (on the original colour scheme). If the mood name could be preserved in cleaned_csv or sqllite db, then it would still be available, but I think it's the same schema as Daylio itself? Someone else reverse engineered it by ADB commands I saw? I haven't delved that far into the project yet though.

**Comment by anthx** [comment]
Moods 1 - 5 but multiple labels yes. I'll make a PR and see what you think. Sorry for the delay, I keep forgetting about this project...
